# Generated by Django 4.2.4 on 2023-08-17 06:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("verify", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="extensionid",
            old_name="extension_id",
            new_name="eid",
        ),
    ]
