# Generated by Django 4.2.4 on 2023-08-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WhitelistPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eid", models.CharField(max_length=32)),
                ("domain_cnt", models.IntegerField(default=0)),
                ("payload", models.CharField(max_length=128000)),
            ],
        ),
    ]
